version: '3.1'

services:

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=victorious
 
    web:
        image: dawwebapp52021/victorious
        restart: always
        ports: 
            - "8443:8443"
        links: 
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/victorious?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=pass